sudo: false
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn deploy --settings settings.xml -Prelease
env:
  global:
  # SONATYPE_USERNAME
  - secure: Expvz+Ka6LsGJ9dzDkePEBkRU8tbxFW7N7MH8QFJMpp7h7jik+eJbgCtwwrWYxveg1ZbCgBBNU2qWpWC7yh9K6mqJUYA9ztxFXb8lQyXSvSG73uZhtagKsh08K1YSP44/UcuMG2MnH3tRkR79AFG4rNJSRzWPe6HKOYfdQicgwI=
  # SONATYPE_PASSWORD
  - secure: epPhyrR2ilYqNfV4+TbrTGjxCbij9P7mofQ2X4nRP2uxEnAFSfANd0/U2MYiv0LcdO+CaHuQwuH3hRboPGtivekDVB0aKSx/D7Qkb9Uv9EQTY4/MmgvBQ1Rkt+ZYOSDv2BdFjTLlxy70nLjZgXGZkOkHIezIukdcF7RB//5BX6Y=
  # GPG_PASSPHRASE
  - secure: o8t3K8UJpqIpJxRG6IYP25SweD4XyjvqKK5tpvRVKSi3XsY1sPbV3/y3jj95jDV2VLYyIDEliGxswB8tsNDzMJqeE7iL3y0L+jSgHvTwJNAGHgKakhFU8cld69dyKxYlxBMb6YM8x07yOJfgd2q2BXc8u48p7M7jGeH4p96VQ5g=
  # GPG_KEYID
  - secure: OJvsrr78j7YU8huHB+o/y9qwK68XBaHOz7TuyIFTz7prIXbQFeBUuiW/D/cS2+qecwPi2MbZZESmRc97pCMUPs9IZAfsqzWv/wWxdRQReKBwWMCTz3GMaoE2j0ZATVZMQohBra+/MXWMq6NEbyauRPtQhxgkf9DNd3Hj06NVhQg=
  # GPG_KEY
  - secure: U7kLh3YgKUNYZ2oD1miZrq0itPtNYOrTJx1uq1TlJWK037f08K3C0FF34Iy6T1pUPJ6wp8Q3p4m+0FoCLTy4GrxcERzC3DTb18gy4iHvkR7NlG1f6Em/gLvIk6Y+3dVLO2uVd/1S+rjFAw7BEduZPQ+8/H99VU34e4yGAbMDBis=
