language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-file tmp.txt secret.gpg.gpg
script: mvn deploy -Prelease
env:
  global:
  # SONATYPE_USERNAME
  - secure: HEqU9CbwFY3KgFA361DMLUq+YcNvUZyU/Bb+E/uoDMblWQqQW5+WZOcXu03swd7R0rjoJH1ECLybD2ziNgUz6Y9Godv0fGKwoGXkH2ucdBUFZq7v7X8kBT0XyUrGCJfaT4SPh2IFosh7JB9fcrGBJE7YxfErsP1KLNUh2t8GPrs=
  # SONATYPE_PASSWORD
  - secure: adc/LWRo8tpdAHAWLmLz/3BycMswdVFcu5A9Y8UiponCKYEPkAg3BjTqAoFaHPPa4wAYRnQ8Ot6soQgvPfdni/ilI07dpeN3GGyfggdCxUv7ZFOseGG1nTkPhjXLQFmQCBUDQYVH+5IaF3tepQC5ZPEnZ1moZV4bZvZ67Axv0Xs=
  # GPG_PASSPHRASE
  - secure: TewxHEPBZKVAQMH6C3Cc5Q4iCYst3iQ/kX+MO5XumOKJnqddickhNbiN5ApvyV6S03XVaggcRvsNGnMcmaHCddFYLVkaQsqX8voUGaAF7DQ8mIkiBmOVFzlDwsCRUV5lDG5V7Ia08OH5cZwsck+D1XtsjfiM1f/cDhLE2l5m8uw=
  # GPG_KEYID
  - secure: RwiVKFqJR62TEff+JWaUiosboVUkjt7BNqC1Dzke4++IcF0Ovwxu2jDH7rL/iVKrXme0MB1M25eUxgst+6zjrDc6g61as+5nMU0F8Sy1u5LByQam+fYz8VAdilcD1EdJ/IFemep18OCmHShZSS9EttGey47Of0cBkogmndv17ro=
  #OPENSSL_KEY
  - secure: YuOx+b1EpxqCUdAcQh8Yg+bXNBBaN/5TncSEqXkN9I3MeXNVqGDkt2WjEtrOQixbWxMkqOO6kMb4MHTqtzj/yFp+aBdvbiIBSzNWURBUbQhNxvrqKCymDfHMZpCoDNbfJGIuH6uV+d/FE7SyHoyTFyp9bEZQ5xq8sBhu3jqiHcc=
  #OPENSSL_IV
  - secure: TlcVxZVchP5f7CXBb+aDvm+XNZv1jgefVHb0Qfy2xxhyuQ49cAvI2PdRQn1CxtQfaWQys+l7euDKvep+mgwm0ASj2t6TUJX5Snm5dbGM9UZTwTRYV4KP876AEPFLqs+I8oPzAFkSES5WPZJU9/Voh2Y9gAa0STzklA4RGCz7OlQ=
  #GPG_KEY
  - secure: bONph+1GT9WZjuxg1BqYHzXqnsULV1NGqk55xGaxLy4xHTj4t1a40zKTSZwVDkQa7RcdGMX8aMlOZ5+5KU3W/eNAn3V5y1FAplNvlHKGe6Dja4+4Hq3wAkuLauBr8X4j4tbUqUP2HUCWC7Uc/VHFgLbtGgI59HHGdMfN1mHX9XE=
